### ISSUE TITLE
Getting the Paper Status?

### ISSUE THREAD

**Issue by crecord** [bakercp/ofxESCPOS#3]
Hi Chris, 

I'm reinstalling my printing sculpture and I am trying to get it so that it handles being out of paper better. I've been messing around with getPrinterStatusRealTime(); but it doesn't seem to report when there is and is not paper. 

I got excited about ".getPaperStatus()" but it does not appear that that function is written.

Any advice on how I might accurately detect when the printer is out of paper? 
(I have one of your Epson ReadyPrint T20)

Much Thanks,
Caroline Record 

for reference here is the piece I am reinstalling:
![img_5150](https://cloud.githubusercontent.com/assets/3160465/4229875/48eeade0-397a-11e4-814a-33386c00c791.jpg)

**Comment by bakercp** [comment]
I use this driver on macos:

https://www.mac-usb-serial.com/

Turns out my RS232 to USB from monoprice probably had counterfit PS2303 chips so the prolific driver wasn't working reliably.  Once I started using that driver on macos, I didn't have problems.  I never had problems with the native linux drivers which are not provided by prolific.
